# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonized_api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
