# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonized_api_rest', '0003_auto_20160824_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
